In [197]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [198]:
# x is a 2-D array with all elements equal to 1 using the `ones` function in numpy library
x=np.ones([6,5])
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [199]:
# y is a 2-D array with all elements equal to 0 using the `full` function in numpy library
x = np.full([6,5],1)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Q#2: Create y array with elements equal to 0.

In [200]:
# y is a 2-D array with all elements equal to 0 using the `zeros` function in numpy library
y = np.zeros([6,5])
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [201]:
# y is a 2-D array with all elements equal to 0 using the `full` function in numpy library
y = np.full([6,5],0)
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Q#3: Add x and y arrays.

In [202]:
x+y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [203]:
print("The dimension: ",x.ndim,"\nThe shape: ",x.shape,"\nThe size: ",x.size,"\nThe type: ",x.dtype)

The dimension:  2 
The shape:  (6, 5) 
The size:  30 
The type:  int64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [204]:
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [205]:
w=np.arange(11,17).reshape(3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [206]:
z=np.array([1,2,3])
z

array([1, 2, 3])

In [207]:
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [208]:
# first solution
# to horizontally stack two arrays, they must be at same number of rows.
# I used reshape function for `z` array to be the same number of rows to `w` array
newArray = np.hstack((z.reshape(3, 1), w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [209]:
#second solution
# I used reshape function for `w` array to be the same number of rows to `z` array
#newArray = np.hstack((z, w.reshape(6)))
#newArray

## Q#8: Print all elements of "newArray" using the loop.

In [210]:
for i in np.nditer(newArray):
  print(i,"\n")

1 

11 

12 

2 

13 

14 

3 

15 

16 



In [211]:
for i in np.nditer(newArray):
    print(i,"\n")

1 

11 

12 

2 

13 

14 

3 

15 

16 



## Q#9: Reverse the columns and rows of "newArray".

In [212]:
reversedArray=newArray[::-1,::-1]
reversedArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

In [213]:
newArray,reversedArray

(array([[ 1, 11, 12],
        [ 2, 13, 14],
        [ 3, 15, 16]]),
 array([[16, 15,  3],
        [14, 13,  2],
        [12, 11,  1]]))

## Q#10: Decrement all elements of "newArray" with 1.

In [214]:
newArray=newArray-1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [215]:
smallestItem=np.min(newArray)
biggestItem=np.max(newArray)
smallestItem,biggestItem

(0, 15)

## Q#12: Print the first row of "newArray" using indexing.

In [216]:
print(newArray[0,:])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [217]:
# fist solution
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [218]:
# fist solution
print(newArray[0,0],newArray[1,2])


0 13


In [219]:
# second solution
print(newArray[[0,1],[0,2]])

[ 0 13]


## Q#15: Change the shape of "newArray" to (9,1).

In [220]:
newArray.shape

(3, 3)

In [221]:
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [222]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

In [223]:
newArray.shape

(3, 3)

## Q#16: Change the shape of "newArray" to (3,2).

In [224]:
# the shape 3,2 means we must have 3 rows, and eaxh row must has 2 item (3 rows and 2 columns)
# that will end up to 6 iems in total, but actually we have 9 items, so we can not reshape this array to 3,2
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉