# Q1: Import numpy library

In [2]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [3]:
sequence = np.linspace(0, 1, 15)
print(sequence)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:
arr=np.array([[[1.1,2.1,3.1],[4.1,5.1,6.1]],[[7.1,8.1,9.1],[10.1,11.1,12.1]]])
print(arr)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [5]:
print("The dimension: ",arr.ndim,"\nThe shape: ",arr.shape,"\nThe size: ",arr.size,"\nThe type: ",arr.dtype)

The dimension:  3 
The shape:  (2, 2, 3) 
The size:  12 
The type:  float64


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes.
- Print the new array's dimention and shape.

In [6]:
arrd4=np.expand_dims(arr,axis=0)
print("The dimension: ",arrd4.ndim,"\nThe shape: ",arrd4.shape)

The dimension:  4 
The shape:  (1, 2, 2, 3)


In [7]:
arrd4

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes.
- Print the new array.

In [8]:
newArray=arrd4.astype(int)
print(newArray)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [9]:
for i in np.nditer(newArray):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [10]:
print(newArray[0,1,0,1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [11]:
print(newArray[0,0,1,1],newArray[0,0,1,2])

5 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [12]:
i8=np.where(newArray==8)
print(i8)

(array([0]), array([1]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [14]:
newArray.shape

(1, 2, 2, 3)

In [15]:
newArray.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis

In [17]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [19]:
arr1,arr2

(array([['A', 'B'],
        ['E', 'F']], dtype='<U1'),
 array([['C', 'D'],
        ['G', 'H']], dtype='<U1'))

In [18]:
arr3=np.concatenate((arr1,arr2))
print(arr3)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1

In [23]:
s = np.concatenate((arr1, arr2), axis=1)
print(s)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays.
Note: use the same array from Q12.1

In [25]:
arr4=np.array_split(arr3,2,axis=1)
arr4

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]